### PR TITLE
Major CSS Update

### PR DESCRIPTION
**Pull request by nobodywasishere**
a545b9b230e1af1a95d80351dc4a595cfca3eec5 will break old system - just need to move user folders assuming I found all locations

The logo was made using public domain assets so there's no strings attached to using it.

### CODE REVIEW

**Comment by stevenbell** [comment]
Glad to see you're hacking on this; this looks cool!

Can you explain the reason for a545b9b?  The way I've been running it, all the users are stored in a separate data directory... maybe I've misunderstood something?

What are all the icon files for?  Is this if the website is saved as an app on mobile?

**Comment by nobodywasishere** [comment]
Thank you! I hope my contributions help other students in the future.

a545b9b230e1af1a95d80351dc4a595cfca3eec5 was to clean up the main folder. All the users are still stored in separate data directories, just within the users folder so they're all in one place and not mingling with the other files of the website. It also provides one folder to add to the .gitignore so that user submissions aren't caught by git, and one folder to archive or delete whenever necessary. If I misunderstood something about how this is run please let me know

The icons are just the standard stuff produced by your typical [favicon generator](https://www.favicon-generator.org/), I just have a habit of including them all just in case. Currently only favicon.ico (it's the little icon on the tab) and one of the apple ones (on the main page) are being used. They may also be used if someone adds it as a web app on their smartphone (not 100% sure about this though). Don't take up very much space and good to have around when you need them.

**Comment by nobodywasishere** [comment]
I need to do more testing on this before this can be merged. Apologies.

**Comment by stevenbell** [comment]
Ah, I see.  That's the point of the `WORKDIR` directory in the configuration.  Usually it's somewhere completely outside the source tree -- the current server has a "beta" and "production" instance which both use the same data directory.

Is it ok if I cherry-pick stuff from your fork?

**Comment by nobodywasishere** [comment]
Ah. I'm silly. That makes perfect sense. I'm reopening this PR. I enabled it so you could make commits to this PR if there's something you wanted to change. 

If you want to see it in action, I have a test server running right now at http://vhdlweb.eowyn.net/ if you want to try out what's currently running from my repo (currently GHDL isn't working corrently so trying to test code itself won't work, but it'll do perfectly for testing the css/html layout on a variety of devices).

Currently on mobile devices everything is too small. Maybe if we did something like [this](https://stackoverflow.com/a/44663015) and CSS custom properties to dynamically change the size of elements if the device is a mobile device?

**Comment by stevenbell** [comment]
I've manually applied most of this PR in c98dc0cdd8c476415c8ae60ba6e3fdbea9c13b67 and 9723ac57a8fc1af83ebd837b005f413b6a14c0ca , so I'm going to close this.

Thanks for your work on this CSS!  One of my goals has been to make it responsive on small screens, and this is a huge leap forward.

**Pull request closed without merging**
